"""Initial migration

Revision ID: 34ffeaf41821
Revises: 
Create Date: 2025-05-24 00:48:28.427886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34ffeaf41821'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('teacher_profile', sa.String(length=255), nullable=True))

    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_constraint('programs_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.create_unique_constraint('programs_name_key', ['name'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('teacher_profile')
        batch_op.drop_column('created_by')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
