"""Add transcription_enabled field to consultation sessions

Revision ID: add_transcription_enabled
Revises: remove_teacher_profile
Create Date: 2025-07-23 21:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_transcription_enabled'
down_revision = 'remove_teacher_profile'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultation_sessions', sa.Column('transcription_enabled', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultation_sessions', 'transcription_enabled')
    # ### end Alembic commands ###
