"""Add ConcernCategory table for Gemini optimization

Revision ID: concern_optimization_001
Revises: f8357eda4ab6
Create Date: 2025-08-20 11:20:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'concern_optimization_001'
down_revision = 'f8357eda4ab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concern_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('normalized_concern', sa.String(length=500), nullable=False),
    sa.Column('original_concern', sa.String(length=500), nullable=False),
    sa.Column('sentencing_category', sa.String(length=300), nullable=True),
    sa.Column('general_category', sa.String(length=100), nullable=True),
    sa.Column('frequency_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() AT TIME ZONE 'UTC')"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concern_categories_normalized_concern'), 'concern_categories', ['normalized_concern'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_concern_categories_normalized_concern'), table_name='concern_categories')
    op.drop_table('concern_categories')
    # ### end Alembic commands ###
